import {
  HomeIcon, BellIcon, UsersIcon, UserPlusIcon,
  DocumentTextIcon, ShoppingBagIcon, DocumentIcon,
  CurrencyDollarIcon, ArrowUturnLeftIcon, ArchiveBoxIcon,
  TagIcon, BuildingOfficeIcon, InboxArrowDownIcon,
  ArrowRightCircleIcon, ArrowsRightLeftIcon, RectangleGroupIcon,
  CubeIcon, BriefcaseIcon, LifebuoyIcon, TicketIcon,
  ShieldCheckIcon, TruckIcon, ReceiptPercentIcon,
  FolderIcon, ChartBarIcon, ArrowTrendingUpIcon,
  BanknotesIcon, BookOpenIcon, CogIcon, ClipboardDocumentListIcon,
} from '@heroicons/vue/24/outline';

export const icons = {
  'home':               HomeIcon,
  'bell':               BellIcon,
  'users':              UsersIcon,
  'user-add':           UserPlusIcon,
  'document-text':      DocumentTextIcon,
  'shopping-bag':       ShoppingBagIcon,
  'document':           DocumentIcon,
  'currency-dollar':    CurrencyDollarIcon,
  'reply':              ArrowUturnLeftIcon,
  'archive':            ArchiveBoxIcon,
  'tag':                TagIcon,
  'office-building':    BuildingOfficeIcon,
  'inbox':              InboxArrowDownIcon,
  'arrow-circle-right': ArrowRightCircleIcon,
  'switch-horizontal':  ArrowsRightLeftIcon,
  'collection':         RectangleGroupIcon,
  'cube':               CubeIcon,
  'briefcase':          BriefcaseIcon,
  'support':            LifebuoyIcon,
  'ticket':             TicketIcon,
  'shield-check':       ShieldCheckIcon,
  'truck':              TruckIcon,
  'receipt-tax':        ReceiptPercentIcon,
  'folder':             FolderIcon,
  'chart-bar':          ChartBarIcon,
  'trending-up':        ArrowTrendingUpIcon,
  'banknotes':          BanknotesIcon,
  'book-open':          BookOpenIcon,
  'cog':                CogIcon,
  'clipboard-list':     ClipboardDocumentListIcon,
};
